version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/fetch_params.sh
      timeout: 60
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
