spring:
  application:
    name: b-live-api
  mvc:
    cors:
      mappings:
        [/**]:
          allowed-origins: http://localhost:3000,https://api.ah.r-e.kr
          allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
          allowed-headers: "*"
          allow-credentials: true
          max-age: 3600
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

