spring:
  application:
    name: b-live-api
  config:
    import: "optional:aws-parameterstore:/blive/prod/"
  mvc:
    cors:
      mappings:
        "[/**]":
          allowed-origins: "http://localhost:3000,https://api.ah.r-e.kr"
          allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
          allowed-headers: "*"
          allow-credentials: true
          max-age: 3600
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cloud:
    aws:
      region:
        static: ap-northeast-2

logging:
  file:
    name: /home/ubuntu/log/b-live-api.log
  level:
    io:
      awspring:
        cloud: debug

